l_english:
 
  is_your_child_desc: "Là con của Ngài"
  is_your_close_family_desc: "Là người thân cận của Ngài"
  is_your_house_desc: "Thuộc Gia tộc của Ngài"
  landed_spouse_desc: "Có Phối ngẫu sở hữu đất"
  landed_heir_desc: "Có Người thừa kế sở hữu đất"
  has_many_good_relations_desc: "Có nhiều bằng hữu"
  has_many_bad_relations_desc: "Bị bao vây bởi Kình địch"
  part_of_feud_desc: "Là một phần của Mối thù truyền kiếp"
  high_diplomacy_desc: "Ngoại giao cao"
  high_martial_desc: "Quân sự cao"
  high_stewardship_desc: "Quản lý cao"
  high_intrigue_desc: "Mưu lược cao"
  high_learning_desc: "Học vấn cao"
  high_prowess_desc: "Dũng mãnh cao"
  high_education_desc: "Được giáo dục xuất sắc"
  more_beautiful_desc: "Xinh đẹp hơn Người thừa kế"
  more_smart_desc: "Thông minh hơn Người thừa kế"
  more_fit_desc: "Khỏe mạnh hơn Người thừa kế"
  more_strong_desc: "Mạnh mẽ hơn Người thừa kế"
  more_skillful_desc: "Thành thạo hơn Người thừa kế"
  has_nickname_desc: "Có biệt danh"
  more_famous_desc: "Nổi tiếng hơn Người thừa kế"
  second_in_line_desc: "Thứ hai trong hàng thừa kế"
  higher_title_desc: "Nắm giữ tước vị cao hơn"
  new_liege_desc: "Sẽ thuộc về Lãnh chúa mới"
  new_top_liege_desc: "Sẽ thuộc về Đại Lãnh chúa mới"
  tall_claims_desc: "Nắm giữ Yêu sách quan trọng"
  pressed_claims_desc: "Nắm giữ Yêu sách đã được thúc đẩy"
  unpressed_claims_desc: "Nắm giữ Yêu sách chưa được thúc đẩy"
  inheritance_line_desc: "Nằm trong hàng thừa kế"
  has_interesting_story_desc: "Có câu chuyện thú vị"
  child_of_destiny_desc: "Là Đứa trẻ Định mệnh"
  virtues_interesting_desc: "Có Đức hạnh"
  tourney_xp_desc: "Có kinh nghiệm [GetTrait('tourney_participant').GetName( GetNullCharacter )]"
  reveler_xp_desc: "Có kinh nghiệm [GetTrait('lifestyle_reveler').GetName( GetNullCharacter )]"
  mystic_xp_desc: "Có kinh nghiệm với vai trò [GetTrait('lifestyle_mystic').GetName( GetNullCharacter )]"
  hunter_xp_desc: "Có kinh nghiệm [GetTrait('lifestyle_hunter').GetName( GetNullCharacter )]"
  blademaster_xp_desc: "Có kinh nghiệm [GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )]"
  traveler_xp_desc: "Có kinh nghiệm [GetTrait('lifestyle_traveler').GetName( GetNullCharacter )]"
  physician_xp_desc: "Có kinh nghiệm [GetTrait('lifestyle_physician').GetName( GetNullCharacter )]"
  herbalist_xp_desc: "Có kinh nghiệm [GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )]"
  loyal_interesting_desc: "Là người [GetTrait('loyal').GetName( GetNullCharacter )]"
  disloyal_interesting_desc: "Là kẻ [GetTrait('disloyal').GetName( GetNullCharacter )]"
  faith_warrior_interesting_desc: "Là một [GetTrait('faith_warrior').GetName( GetNullCharacter )]"
  blood_of_prophet_interesting_desc: "Mang [GetTrait('blood_of_prophet').GetName( GetNullCharacter )]"
  varangian_interesting_desc: "Là một [GetTrait('varangian').GetName( GetNullCharacter )]"
  poet_interesting_desc: "Là một [GetTrait('lifestyle_poet').GetName( GetNullCharacter )]"
  peasant_leader_interesting_desc: "Là một [GetTrait('peasant_leader').GetName( GetNullCharacter )]"
  populist_leader_interesting_desc: "Là một [GetTrait('populist_leader').GetName( GetNullCharacter )]"
  berserker_interesting_desc: "Là một [GetTrait('berserker').GetName( GetNullCharacter )]"
  born_in_the_purple_interesting_desc: "Là [GetTrait('born_in_the_purple').GetName( GetNullCharacter )]"
  scaly_interesting_desc: "Có làn da [GetTrait('scaly').GetName( GetNullCharacter )]"
  albino_interesting_desc: "Là người [GetTrait('albino').GetName( GetNullCharacter )]"
  dwarf_interesting_desc: "Là người [GetTrait('dwarf').GetName( GetNullCharacter )]"
  giant_interesting_desc: "Là người [GetTrait('giant').GetName( GetNullCharacter )]"
  devoted_interesting_desc: "Là một [GetTrait('devoted').GetName( GetNullCharacter )]"
  pure_blooded_interesting_desc: "Là [GetTrait('pure_blooded').GetName( GetNullCharacter )]"
  crusader_king_interesting_desc: "Là một [GetTrait('crusader_king').GetName( GetNullCharacter )]"
  disinherited_interesting_desc: "Là [GetTrait('disinherited').GetName( GetNullCharacter )]"
  blind_interesting_desc: "Là [GetTrait('blind').GetName( GetNullCharacter )]"
  is_diarch_interesting_desc: "Là Đồng chấp chính"
  ruler_in_foreign_lands_interesting_desc: "Là Nhà cai trị ở vùng đất ngoại bang"
  valiant_knight_interesting_desc: "Là Hiệp sĩ dũng cảm"
  sinful_bastard_interesting_desc: "Là một [GetTrait('bastard').GetName( GetNullCharacter )] tội lỗi"
  adventurer_interesting_desc: "Là Nhà phiêu lưu"
  liege_crusader_king_liege_lineage_interesting_desc: "Lãnh chúa thuộc dòng dõi [GetTrait('crusader_king').GetName( GetNullCharacter )]"
  holy_site_steward_interesting_desc: "Thủ đô là Thánh địa"
  has_a_legend_interesting_desc: "Có một Huyền thoại"
  weak_hook_liege_interesting_desc: "Có Móc yếu với Lãnh chúa"
  strong_hook_liege_interesting_desc: "Có Móc mạnh với Lãnh chúa"
  beloved_by_pope_interesting_desc: "Được Giáo hoàng yêu mến"
  head_of_faith_interesting_desc: "Là Lãnh đạo Tôn giáo"
  stronger_than_liege_interesting_desc: "Mạnh hơn Lãnh chúa"
  small_king_interesting_desc: "Là người cai trị một Vương quốc nhỏ"
  can_feudalize_interesting_desc: "Có thể phong kiến hóa"
  multiduke_interesting_desc: "Nắm giữ nhiều Công quốc"
  legitimacy_interesting_desc: "Nhà cai trị có tính chính danh cực cao"
  non_dominant_gender_ambitious_char_interesting_desc: "Là nhân vật giới không thống trị đầy tham vọng"
  non_dominant_gender_ruler_interesting_desc: "Là Nhà cai trị thuộc giới không thống trị"
  treacherous_schemer_interesting_desc: "Là Kẻ âm mưu phản trắc"
  kind_hearted_diplomat_interesting_desc: "Là Nhà ngoại giao nhân hậu"
  different_faith_interesting_desc: "Thuộc Tôn giáo khác"
  greedy_steward_interesting_desc: "Là Quản gia tham lam"
  brazen_commander_interesting_desc: "Là Chỉ huy táo bạo"
  pious_theologian_interesting_desc: "Là Nhà thần học sùng đạo"
  salacious_seducer_interesting_desc: "Là Kẻ quyến rũ dâm đãng"
  high_skills_desc: "Kỹ năng rất cao"
  killed_a_lot_interesting_desc: "Đã giết hơn 10 người"
  has_both_good_and_bad_genetics_desc: "Có cả đặc tính di truyền tốt và xấu"
  good_genetics_desc: "Đặc tính di truyền tốt"
  bad_genetics_desc: "Đặc tính di truyền xấu"
  holds_rome_interesting_desc: "Nắm giữ [GetTitleByKey('c_roma').GetBaseName]"
  holds_byzantion_interesting_desc: "Nắm giữ [GetTitleByKey('c_byzantion').GetBaseName]"
  holds_jerusalem_interesting_desc: "Nắm giữ [GetTitleByKey('c_jerusalem').GetBaseName]"
  holds_mecca_interesting_desc: "Nắm giữ [GetTitleByKey('c_mecca').GetBaseName]"
  holds_baghdad_interesting_desc: "Nắm giữ [GetTitleByKey('c_baghdad').GetBaseName]"
  holds_special_buildings_interesting_desc: "Kiểm soát Công trình Đặc biệt"
  has_historical_artifacts_interesting_desc: "Sở hữu Cổ vật Lịch sử độc nhất"
  underrepresented_faith_interesting_desc: "Thuộc Tôn giáo thiểu số"
  underrepresented_culture_interesting_desc: "Thuộc Văn hóa thiểu số"
  outside_realm_desc: "Nhà cai trị độc lập"
  knows_many_secrets_interesting_desc: "Biết nhiều Bí mật"
  has_secrets_interesting_desc: "Có Bí mật"
  extremely_wealthy_interesting_desc: "Rất giàu có"
  landless_heir_uninteresting_desc: "Người thừa kế không có đất"
  three_virtues_desc: "Có ba Đức hạnh"
  three_sins_desc: "Có ba Tội lỗi"

  skills_difficulty: "Từ Kỹ năng"
  legitimacy_difficulty: "Từ Tính chính danh"
  virtuous_traits_difficulty: "Có Đặc tính Đức hạnh"
  physique_good_3_difficulty: "Là [GetTrait('physique_good_3').GetName( GetNullCharacter )]"
  physique_good_2_difficulty: "Là [GetTrait('physique_good_2').GetName( GetNullCharacter )]"
  physique_good_1_difficulty: "Là [GetTrait('physique_good_1').GetName( GetNullCharacter )]"
  intellect_good_3_difficulty: "Là [GetTrait('intellect_good_3').GetName( GetNullCharacter )]"
  intellect_good_2_difficulty: "Là [GetTrait('intellect_good_2').GetName( GetNullCharacter )]"
  intellect_good_1_difficulty: "Là [GetTrait('intellect_good_1').GetName( GetNullCharacter )]"
  beauty_good_3_difficulty: "Là [GetTrait('beauty_good_3').GetName( GetNullCharacter )]"
  beauty_good_2_difficulty: "Là [GetTrait('beauty_good_2').GetName( GetNullCharacter )]"
  beauty_good_1_difficulty: "Là [GetTrait('beauty_good_1').GetName( GetNullCharacter )]"
  shrewd_difficulty: "Là [GetTrait('shrewd').GetName( GetNullCharacter )]"
  strong_difficulty: "Là [GetTrait('strong').GetName( GetNullCharacter )]"
  sinful_traits_difficulty: "Có Đặc tính Tội lỗi"
  incapable_difficulty: "Là [GetTrait('incapable').GetName( GetNullCharacter )]"
  leper_difficulty: "Là một [GetTrait('leper').GetName( GetNullCharacter )]"
  maimed_difficulty: "Là [GetTrait('maimed').GetName( GetNullCharacter )]"
  inbred_difficulty: "Là [GetTrait('inbred').GetName( GetNullCharacter )]"
  severely_wounded_difficulty: "Bị thương nặng"
  disinherited_difficulty: "Là [GetTrait('disinherited').GetName( GetNullCharacter )]"
  sickly_difficulty: "Là [GetTrait('sickly').GetName( GetNullCharacter )]"
  poxed_difficulty: "Mắc [GetTrait('great_pox').GetName( GetNullCharacter )]"
  blind_difficulty: "Là [GetTrait('blind').GetName( GetNullCharacter )]"
  infirm_difficulty: "Là [GetTrait('infirm').GetName( GetNullCharacter )]"
  eunuch_difficulty: "Là một [GetTrait('eunuch_1').GetName( GetNullCharacter )]"
  lunatic_difficulty: "Là một [GetTrait('lunatic').GetName( GetNullCharacter )]"
  murderer_difficulty: "Là một [GetTrait('murderer').GetName( GetNullCharacter )]"
  excommunicated_difficulty: "Bị rút phép thông công"
  bleeder_difficulty: "Là một [GetTrait('bleeder').GetName( GetNullCharacter )]"
  physique_bad_3_difficulty: "Là [GetTrait('physique_bad_3').GetName( GetNullCharacter )]"
  physique_bad_2_difficulty: "Là [GetTrait('physique_bad_2').GetName( GetNullCharacter )]"
  physique_bad_1_difficulty: "Là [GetTrait('physique_bad_1').GetName( GetNullCharacter )]"
  intellect_bad_3_difficulty: "Là [GetTrait('intellect_bad_3').GetName( GetNullCharacter )]"
  intellect_bad_2_difficulty: "Là [GetTrait('intellect_bad_2').GetName( GetNullCharacter )]"
  intellect_bad_1_difficulty: "Là [GetTrait('intellect_bad_1').GetName( GetNullCharacter )]"
  beauty_bad_3_difficulty: "Là [GetTrait('beauty_bad_3').GetName( GetNullCharacter )]"
  beauty_bad_2_difficulty: "Là [GetTrait('beauty_bad_2').GetName( GetNullCharacter )]"
  beauty_bad_1_difficulty: "Là [GetTrait('beauty_bad_1').GetName( GetNullCharacter )]"
  dull_difficulty: "Là [GetTrait('dull').GetName( GetNullCharacter )]"
  weak_difficulty: "Là [GetTrait('weak').GetName( GetNullCharacter )]"
  sodomite_difficulty: "Là một [GetTrait('sodomite').GetName( GetNullCharacter )]"
  incestuous_difficulty: "Là [GetTrait('incestuous').GetName( GetNullCharacter )]"
  fornicator_difficulty: "Là một [GetTrait('fornicator').GetName( GetNullCharacter )]"
  adulterer_difficulty: "Là một [GetTrait('adulterer').GetName( GetNullCharacter )]"
  cannibal_difficulty: "Là một [GetTrait('cannibal').GetName( GetNullCharacter )]"
  witch_difficulty: "Là một [GetTrait('witch').GetName( GetNullCharacter )]"
  kinslayer_difficulty: "Là một [GetTrait('kinslayer_1').GetName( GetNullCharacter )]"
  flagellant_difficulty: "Là một [GetTrait('flagellant').GetName( GetNullCharacter )]"
  improvident_difficulty: "Là [GetTrait('improvident').GetName( GetNullCharacter )]"
  profligate_difficulty: "Là [GetTrait('profligate').GetName( GetNullCharacter )]"
  disfigured_difficulty: "Là [GetTrait('disfigured').GetName( GetNullCharacter )]"
  drunkard_difficulty: "Là một [GetTrait('drunkard').GetName( GetNullCharacter )]"
  possessed_difficulty: "Là [GetTrait('possessed').GetName( GetNullCharacter )]"
  depressed_difficulty: "Là [GetTrait('depressed').GetName( GetNullCharacter )]"
  infertile_difficulty: "Là [GetTrait('infertile').GetName( GetNullCharacter )]"
  spindly_difficulty: "Là [GetTrait('spindly').GetName( GetNullCharacter )]"
  paranoid_difficulty: "Là [GetTrait('paranoid').GetName( GetNullCharacter )]"
  gout_difficulty: "Mắc [GetTrait('gout_ridden').GetName( GetNullCharacter )]"
  wheezing_difficulty: "Là [GetTrait('wheezing').GetName( GetNullCharacter )]"
  craven_difficulty: "Là [GetTrait('craven').GetName( GetNullCharacter )]"
  shy_difficulty: "Là [GetTrait('shy').GetName( GetNullCharacter )]"
  decadent_difficulty: "Là [GetTrait('decadent').GetName( GetNullCharacter )]"
  denounced_difficulty: "Là [GetTrait('denounced').GetName( GetNullCharacter )]"
  bastard_difficulty: "Là một [GetTrait('bastard').GetName( GetNullCharacter )]"
  weak_heritage_difficulty: "Có Huyết thống yếu"
  comfort_eater_difficulty: "Là một [GetTrait('comfort_eater').GetName( GetNullCharacter )]"
  inappetetic_difficulty: "Là [GetTrait('inappetetic').GetName( GetNullCharacter )]"
  reclusive_difficulty: "Là [GetTrait('reclusive').GetName( GetNullCharacter )]"
  irritable_difficulty: "Là [GetTrait('irritable').GetName( GetNullCharacter )]"
  rakish_difficulty: "Là [GetTrait('rakish').GetName( GetNullCharacter )]"
  hashishiyah_difficulty: "Là một [GetTrait('hashishiyah').GetName( GetNullCharacter )]"
  celibate_difficulty: "Là [GetTrait('celibate').GetName( GetNullCharacter )]"
  lovers_pox_difficulty: "Mắc [GetTrait('lovers_pox').GetName( GetNullCharacter )]"
  wounded_difficulty: "Là [GetTrait('wounded_1').GetName( GetNullCharacter )]"
  albino_difficulty: "Là một [GetTrait('albino').GetName( GetNullCharacter )]"
  lisping_difficulty: "Có tật nói [GetTrait('lisping').GetName( GetNullCharacter )]"
  stuttering_difficulty: "Có tật nói [GetTrait('stuttering').GetName( GetNullCharacter )]"
  giant_difficulty: "Là một [GetTrait('giant').GetName( GetNullCharacter )]"
  scaly_difficulty: "Có làn da [GetTrait('scaly').GetName( GetNullCharacter )]"
  clubfooted_difficulty: "Là [GetTrait('clubfooted').GetName( GetNullCharacter )]"
  dwarf_difficulty: "Là một [GetTrait('dwarf').GetName( GetNullCharacter )]"
  hunchbacked_difficulty: "Là [GetTrait('hunchbacked').GetName( GetNullCharacter )]"
  lazy_difficulty: "Là [GetTrait('lazy').GetName( GetNullCharacter )]"
  gluttonous_difficulty: "Là [GetTrait('gluttonous').GetName( GetNullCharacter )]"
  deviant_difficulty: "Là một [GetTrait('deviant').GetName( GetNullCharacter )]"
  at_war_difficulty: "Đang có chiến tranh"
  losing_war_difficulty: "Đang thua chiến tranh"
  faction_difficulty: "Bị các Phe phái quyền lực nhắm tới"
  powerful_neighbors_difficulty: "láng giềng  hùng mạnh"
  military_difficulty: "Sức mạnh quân sự"
  rivals_difficulty: "Có Kình địch"
  primary_heir_wrong_dynasty_difficulty: "Người thừa kế chính sai Triều đại"
  children_wrong_dynasty_difficulty: "Con cái thuộc sai Triều đại"
  hostile_faith_liege_difficulty: "Lãnh chúa theo Tôn giáo thù địch"
  nonpreferred_gender_difficulty: "Giới tính không được ưa chuộng trong Tôn giáo"
  wrong_lineality_difficulty: "Sai hệ kế thừa trong hôn nhân"
  stress_level_difficulty: "Mức Căng thẳng cao"
  gold_difficulty: "Của cải dư thừa"
  debt_level_difficulty: "Mức Nợ cao"
  is_ill_difficulty: "Mắc bệnh suy nhược nghiêm trọng"
  imprisoned_difficulty: "Bị cầm tù"
  elder_difficulty: "Tuổi cao"
  poor_health_difficulty: "Sức khỏe kém"
  is_a_vassal_difficulty: "Là Chư hầu"
  non_adult_difficulty: "Trẻ vị thành niên"
  weak_domain_difficulty: "Lãnh địa yếu"
  unlanded_difficulty: "Không nắm giữ Tước vị"
 
  character_difficulty_text: "Độ khó: [Character.Custom('CharacterDifficulty')]"
  character_difficulty_breakdown_header: "Phân tích Độ khó"
  choose_destiny_header_text: "Chọn một Định mệnh mới"
  will_become_adventurer: "Sẽ trở thành một [GetGovernment('landless_adventurer_government').GetName]"
  character_interest_breakdown_header: "Các yếu tố thú vị"

  different_government_desc: "Có Chính thể khác"
  opposite_struggle_faction_desc: "Thuộc Phe đối lập trong một Cuộc tranh đấu"
