l_english: 
  message_settings_tab_settings: "Cài đặt"
  message_settings_tab_log: "Nhật ký tin nhắn"

  MESSAGE_SETTINGS_WINDOW_NAME: "Cài đặt tin nhắn"
  MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I Nhấp để mở Cài đặt tin nhắn#!"
  MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nChỉnh tần suất và cách hiển thị tin nhắn theo từng nhóm lọc."
  MESSAGE_SETTINGS_WINDOW_RESET: "Khôi phục mặc định"
  MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Khôi phục cài đặt tin nhắn#!\n#I Nhấp để đặt lại các thay đổi hiện tại về mặc định#!"
  MESSAGE_SETTINGS_WINDOW_APPLY: "Áp dụng thay đổi"
  MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Nhấp để đóng cửa sổ Cài đặt tin nhắn và lưu các thay đổi hiện tại#!"
  MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Dòng tin"
  MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Thông báo nhanh"
  MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Cửa sổ bật lên"
  MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Không bao giờ"
  MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
  MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Nhóm lọc"
  MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Tên của nhóm lọc tin nhắn"
  MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Hiển thị"
  MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Cách hiển thị tin nhắn của nhóm lọc này"
  MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Tạm dừng"
  MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Trò chơi có tự động tạm dừng khi xuất hiện tin nhắn của nhóm lọc này hay không"
  MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Bật/Tắt tự động tạm dừng#!\n#I Chuyển để tạm dừng trò chơi khi tin nhắn của nhóm lọc này xuất hiện#!"
  MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Đóng tin nhắn#!\n#I Nhấp để đóng tin nhắn hiện tại và hiển thị tin nhắn tiếp theo trong hàng đợi#!"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "Tin nhắn tùy chỉnh"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T Tin nhắn tùy chỉnh#!\n#I Nhấp để viết một tin nhắn cho chính Ngài và chọn thời điểm nhận#!"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "Ngày nhận: [DATE.GetString|V]"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "Tiêu đề:"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "Nội dung:"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "Hủy bỏ"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T Hủy tin nhắn#!\n#I Nhấp để hủy tin nhắn hiện tại#!"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "Gửi"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T Gửi#!\n#I Nhấp để gửi tin nhắn hiện tại#!"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "Ngày"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "Tháng"
  MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "Năm"
